import { Injectable } from "@nestjs/common";

@Injectable()
export default class AppPermit {

    public readonly SUPER_ADMIN             = `SUPER_ADMIN`;
    public readonly COODINADOR              = `COODINADOR`;
    public readonly ESTUDIANTE              = `ESTUDIANTE`;
    public readonly OBRERO_ADMINISTRATIVO   = `OBRERO_ADMINISTRATIVO`;
    public readonly ANALISTA                = `ANALISTA`;
    public readonly DOCENTE                 = `DOCENTE`;

    public GetPermitAnalista () {
        return [
            ...this.APP_DEFAULT_PERMIT,
            this.APP_PERMIT_ANALITIC_SECTION,
            this.APP_PERMIT_CONFIG_STATE_LIST,
            this.APP_PERMIT_CONFIG_STATE_SHOW,
            this.APP_PERMIT_CONFIG_STATE_REPORT,
            this.APP_PERMIT_CONFIG_MUNICIPIO_LIST,
            this.APP_PERMIT_CONFIG_MUNICIPIO_SHOW,
            this.APP_PERMIT_CONFIG_MUNICIPIO_REPORT,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_LIST,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_SHOW,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_REPORT,
            this.APP_PERMIT_CONFIG_NUCLEOS_LIST,
            this.APP_PERMIT_CONFIG_NUCLEOS_SHOW,
            this.APP_PERMIT_CONFIG_NUCLEOS_REPORT,
            this.APP_PERMIT_COUNT_USER,
            this.APP_PERMIT_COUNT_PROJECTS,
            this.APP_PERMIT_COUNT_PROGRAM,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_PROGRAM,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_CATEGORY,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_LINE,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_HISTORY,
            this.APP_PERMIT_CONFIG_PROGRAM_LIST,
            this.APP_PERMIT_CONFIG_PROGRAM_SHOW,
            this.APP_PERMIT_CONFIG_LINE_LIST,
            this.APP_PERMIT_CONFIG_LINE_SHOW,
            this.APP_PERMIT_PROJECT_REPORT,
            this.APP_PERMIT_PROJECT_LIST,
            this.APP_PERMIT_PROJECT_SHOW,
            this.STATICTICS_CREATE_USER,
            this.STATICTICS_CREATE_USER_STUDENT,
            this.STATICTICS_CREATE_USER_DOCENTE,
            this.STATICTICS_CREATE_USER_COORDINADOR,
            this.STATICTICS_CREATE_USER_OBRERO_ADMIN,
            this.STATICTICS_CREATE_PROJECT,
        ]
    }

    public GetPermitSuperAdmin () {
        return [
            ...this.APP_DEFAULT_PERMIT,
            this.APP_PERMIT_USER_LIST,
            this.APP_PERMIT_ANALITIC_SECTION,
            this.APP_PERMIT_USER_SHOW,
            this.APP_PERMIT_USER_CREATE,
            this.APP_PERMIT_USER_UPDATE,
            this.APP_PERMIT_USER_DELETE,
            this.APP_PERMIT_USER_RECOVERY,
            this.APP_PERMIT_USER_REPORT,
            this.APP_PERMIT_PERMIT_LIST,
            this.APP_PERMIT_PERMIT_SHOW,
            this.APP_PERMIT_PERMIT_CREATE,
            this.APP_PERMIT_PERMIT_UPDATE,
            this.APP_PERMIT_PERMIT_DELETE,
            this.APP_PERMIT_PERMIT_RECOVERY,
            this.APP_PERMIT_PERMIT_REPORT,
            this.APP_PERMIT_CONFIG_CATEGORY_LIST,
            this.APP_PERMIT_CONFIG_CATEGORY_SHOW,
            this.APP_PERMIT_CONFIG_CATEGORY_CREATE,
            this.APP_PERMIT_CONFIG_CATEGORY_UPDATE,
            this.APP_PERMIT_CONFIG_CATEGORY_DELETE,
            this.APP_PERMIT_CONFIG_CATEGORY_RECOVERY,
            this.APP_PERMIT_CONFIG_CATEGORY_REPORT,
            this.APP_PERMIT_CONFIG_PROGRAM_LIST,
            this.APP_PERMIT_CONFIG_PROGRAM_SHOW,
            this.APP_PERMIT_CONFIG_PROGRAM_CREATE,
            this.APP_PERMIT_CONFIG_PROGRAM_UPDATE,
            this.APP_PERMIT_CONFIG_PROGRAM_DELETE,
            this.APP_PERMIT_CONFIG_PROGRAM_RECOVERY,
            this.APP_PERMIT_CONFIG_PROGRAM_REPORT,
            this.APP_PERMIT_CONFIG_LINE_LIST,
            this.APP_PERMIT_CONFIG_LINE_SHOW,
            this.APP_PERMIT_CONFIG_LINE_CREATE,
            this.APP_PERMIT_CONFIG_LINE_UPDATE,
            this.APP_PERMIT_CONFIG_LINE_DELETE,
            this.APP_PERMIT_CONFIG_LINE_RECOVERY,
            this.APP_PERMIT_CONFIG_LINE_REPORT,
            this.APP_PERMIT_PROJECT_LIST,
            this.APP_PERMIT_PROJECT_SHOW,
            this.APP_PERMIT_PROJECT_CREATE,
            this.APP_PERMIT_PROJECT_UPDATE,
            this.APP_PERMIT_PROJECT_DELETE,
            this.APP_PERMIT_PROJECT_RECOVERY,
            this.APP_PERMIT_PROJECT_REPORT,
            this.APP_PERMIT_HISTORY_LIST,
            this.APP_PERMIT_HISTORY_SHOW,
            this.APP_PERMIT_COUNT_USER,
            this.APP_PERMIT_COUNT_PROJECTS,
            this.APP_PERMIT_COUNT_PROGRAM,
            this.APP_PERMIT_STATICTIS_USUARIOS_IN_PERMIT,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_PROGRAM,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_CATEGORY,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_LINE,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_HISTORY,
            this.APP_PERMIT_COUNT_STORAGE,
            this.APP_PERMIT_COUNT_PROJECTS,
            this.APP_PERMIT_COUNT_USER,
            this.APP_PERMIT_COUNT_COORDINADORES,
            this.APP_PERMIT_COUNT_ESTUDIANTES,
            this.APP_PERMIT_CONFIG_STATE_LIST,
            this.APP_PERMIT_CONFIG_STATE_SHOW,
            this.APP_PERMIT_CONFIG_STATE_CREATE,
            this.APP_PERMIT_CONFIG_STATE_UPDATE,
            this.APP_PERMIT_CONFIG_STATE_DELETE,
            this.APP_PERMIT_CONFIG_STATE_RECOVERY,
            this.APP_PERMIT_CONFIG_STATE_REPORT,
            this.APP_PERMIT_CONFIG_STATE_DOWNLOAD,
            this.APP_PERMIT_CONFIG_MUNICIPIO_LIST,
            this.APP_PERMIT_CONFIG_MUNICIPIO_SHOW,
            this.APP_PERMIT_CONFIG_MUNICIPIO_CREATE,
            this.APP_PERMIT_CONFIG_MUNICIPIO_UPDATE,
            this.APP_PERMIT_CONFIG_MUNICIPIO_DELETE,
            this.APP_PERMIT_CONFIG_MUNICIPIO_RECOVERY,
            this.APP_PERMIT_CONFIG_MUNICIPIO_REPORT,
            this.APP_PERMIT_CONFIG_MUNICIPIO_DOWNLOAD,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_LIST,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_SHOW,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_CREATE,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_UPDATE,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_DELETE,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_RECOVERY,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_REPORT,
            this.APP_PERMIT_CONFIG_PARRAOQUIAS_DOWNLOAD,
            this.APP_PERMIT_CONFIG_NUCLEOS_LIST,
            this.APP_PERMIT_CONFIG_NUCLEOS_SHOW,
            this.APP_PERMIT_CONFIG_NUCLEOS_CREATE,
            this.APP_PERMIT_CONFIG_NUCLEOS_UPDATE,
            this.APP_PERMIT_CONFIG_NUCLEOS_DELETE,
            this.APP_PERMIT_CONFIG_NUCLEOS_RECOVERY,
            this.APP_PERMIT_CONFIG_NUCLEOS_REPORT,
            this.APP_PERMIT_CONFIG_NUCLEOS_DOWNLOAD,
            this.APP_PERMIT_COUNT_DOCENTE,
            this.APP_PERMIT_COUNT_OBRERO_ADMIN,
            this.APP_PERMIT_COUNT_ANALISTA,
            this.STATICTICS_CREATE_USER,
            this.STATICTICS_CREATE_USER_STUDENT,
            this.STATICTICS_CREATE_USER_DOCENTE,
            this.STATICTICS_CREATE_USER_COORDINADOR,
            this.STATICTICS_CREATE_USER_OBRERO_ADMIN,
            this.STATICTICS_CREATE_PROJECT,
        ]
    }

    public GetPermitCoordinador () {
        return [
            ...this.APP_DEFAULT_PERMIT,
            this.APP_PERMIT_CONFIG_PROGRAM_LIST,
            this.APP_PERMIT_CONFIG_PROGRAM_CREATE,
            this.APP_PERMIT_USER_LIST,
            this.APP_PERMIT_USER_CREATE,
            this.APP_PERMIT_CONFIG_PROGRAM_SHOW,
            this.APP_PERMIT_CONFIG_LINE_LIST,
            this.APP_PERMIT_CONFIG_LINE_CREATE,
            this.APP_PERMIT_CONFIG_LINE_SHOW,
            this.APP_PERMIT_PROJECT_REPORT,
            this.APP_PERMIT_PROJECT_LIST,
            this.APP_PERMIT_PROJECT_SHOW,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_PROGRAM,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_CATEGORY,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_LINE,
            this.APP_PERMIT_STATICTIS_PROJECTS_IN_HISTORY,
            this.APP_PERMIT_COUNT_USER,
            this.APP_PERMIT_COUNT_ESTUDIANTES,
            this.APP_PERMIT_COUNT_PROJECTS,
        ]
    }

    public GetPermitEstudiante () {
        return [
            ...this.APP_DEFAULT_PERMIT,
            this.APP_PERMIT_PROPIETARY_PROJECT,
            this.APP_PERMIT_PROJECT_CREATE,
            this.APP_PERMIT_PROJECT_SHOW,
            this.APP_PERMIT_PROJECT_LIST,
            this.APP_PERMIT_PROPIETARY_PROJECTS
        ]
    }

    public GetPermitObreroAdmintrativo () {
        return [
            ...this.APP_DEFAULT_PERMIT,
        ]
    }

    public readonly APP_DEFAULT_PERMIT = [
        `APP_PERMIT_PROFILE`,
        `APP_PERMIT_PROFILE_UPDATE`,
        `APP_PERMIT_PROFILE_PASSWORD`,
        `APP_PERMIT_PROFILE_PHOTO`,
    ]

    /**
     * PROPIETARY COUNT
     */
    public readonly APP_PERMIT_PROPIETARY_PROJECTS        = `APP_PERMIT_PROPIETARY_PROJECTS`;

    /**
     * COUNT
     */
    public readonly APP_PERMIT_COUNT_ESTUDIANTES        = `APP_PERMIT_COUNT_ESTUDIANTES`;
    public readonly APP_PERMIT_COUNT_COORDINADORES      = `APP_PERMIT_COUNT_COORDINADORES`;
    public readonly APP_PERMIT_COUNT_DOCENTE            = `APP_PERMIT_COUNT_DOCENTE`;
    public readonly APP_PERMIT_COUNT_OBRERO_ADMIN       = `APP_PERMIT_COUNT_OBRERO_ADMIN`;
    public readonly APP_PERMIT_COUNT_ANALISTA           = `APP_PERMIT_COUNT_ANALISTA`;
    public readonly APP_PERMIT_COUNT_STORAGE            = `APP_PERMIT_COUNT_STORAGE`;
    public readonly APP_PERMIT_COUNT_PROJECT            = `APP_PERMIT_COUNT_PROJECTS`;
    public readonly APP_PERMIT_COUNT_PROGRAMS           = `APP_PERMIT_COUNT_PROGRAM`;


    /**
     * GLOBALES
     */
    // USUARIO [USER]
    public readonly APP_PERMIT_USER_LIST         = `APP_PERMIT_USER_LIST`;
    public readonly APP_PERMIT_USER_SHOW         = `APP_PERMIT_USER_SHOW`;
    public readonly APP_PERMIT_USER_CREATE       = `APP_PERMIT_USER_CREATE`;
    public readonly APP_PERMIT_USER_UPDATE       = `APP_PERMIT_USER_UPDATE`;
    public readonly APP_PERMIT_USER_DELETE       = `APP_PERMIT_USER_DELETE`;
    public readonly APP_PERMIT_USER_RECOVERY     = `APP_PERMIT_USER_RECOVERY`;
    public readonly APP_PERMIT_USER_REPORT      = `APP_PERMIT_USER_REPORT`;

    // USUARIO [PERMIT]
    public readonly APP_PERMIT_PERMIT_LIST         = `APP_PERMIT_PERMIT_LIST`;
    public readonly APP_PERMIT_PERMIT_SHOW         = `APP_PERMIT_PERMIT_SHOW`;
    public readonly APP_PERMIT_PERMIT_CREATE       = `APP_PERMIT_PERMIT_CREATE`;
    public readonly APP_PERMIT_PERMIT_UPDATE       = `APP_PERMIT_PERMIT_UPDATE`;
    public readonly APP_PERMIT_PERMIT_DELETE       = `APP_PERMIT_PERMIT_DELETE`;
    public readonly APP_PERMIT_PERMIT_RECOVERY     = `APP_PERMIT_PERMIT_RECOVERY`;
    public readonly APP_PERMIT_PERMIT_REPORT        = `APP_PERMIT_PERMIT_REPORT`;

    // CATEGORIA [CONFIG_CATEGORY]
    public readonly APP_PERMIT_CONFIG_CATEGORY_LIST         = `APP_PERMIT_CONFIG_CATEGORY_LIST`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_SHOW         = `APP_PERMIT_CONFIG_CATEGORY_SHOW`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_CREATE       = `APP_PERMIT_CONFIG_CATEGORY_CREATE`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_UPDATE       = `APP_PERMIT_CONFIG_CATEGORY_UPDATE`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_DELETE       = `APP_PERMIT_CONFIG_CATEGORY_DELETE`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_RECOVERY     = `APP_PERMIT_CONFIG_CATEGORY_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_CATEGORY_REPORT       = `APP_PERMIT_CONFIG_CATEGORY_REPORT`;

    // PROGRAMA [CONFIG_PROGRAM]
    public readonly APP_PERMIT_CONFIG_PROGRAM_LIST         = `APP_PERMIT_CONFIG_PROGRAM_LIST`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_SHOW         = `APP_PERMIT_CONFIG_PROGRAM_SHOW`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_CREATE       = `APP_PERMIT_CONFIG_PROGRAM_CREATE`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_UPDATE       = `APP_PERMIT_CONFIG_PROGRAM_UPDATE`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_DELETE       = `APP_PERMIT_CONFIG_PROGRAM_DELETE`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_RECOVERY     = `APP_PERMIT_CONFIG_PROGRAM_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_PROGRAM_REPORT        = `APP_PERMIT_CONFIG_PROGRAM_REPORT`;

    // LINEAS DE INVESTIGACIÓN [CONFIG_LINE]
    public readonly APP_PERMIT_CONFIG_LINE_LIST         = `APP_PERMIT_CONFIG_LINE_LIST`;
    public readonly APP_PERMIT_CONFIG_LINE_SHOW         = `APP_PERMIT_CONFIG_LINE_SHOW`;
    public readonly APP_PERMIT_CONFIG_LINE_CREATE       = `APP_PERMIT_CONFIG_LINE_CREATE`;
    public readonly APP_PERMIT_CONFIG_LINE_UPDATE       = `APP_PERMIT_CONFIG_LINE_UPDATE`;
    public readonly APP_PERMIT_CONFIG_LINE_DELETE       = `APP_PERMIT_CONFIG_LINE_DELETE`;
    public readonly APP_PERMIT_CONFIG_LINE_RECOVERY     = `APP_PERMIT_CONFIG_LINE_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_LINE_REPORT       = `APP_PERMIT_CONFIG_LINE_REPORT`;

    // TRABAJOS [PROJECT]
    public readonly APP_PERMIT_PROJECT_LIST         = `APP_PERMIT_PROJECT_LIST`;
    public readonly APP_PERMIT_PROJECT_SHOW         = `APP_PERMIT_PROJECT_SHOW`;
    public readonly APP_PERMIT_PROJECT_CREATE       = `APP_PERMIT_PROJECT_CREATE`;
    public readonly APP_PERMIT_PROJECT_UPDATE       = `APP_PERMIT_PROJECT_UPDATE`;
    public readonly APP_PERMIT_PROJECT_DELETE       = `APP_PERMIT_PROJECT_DELETE`;
    public readonly APP_PERMIT_PROJECT_RECOVERY     = `APP_PERMIT_PROJECT_RECOVERY`;
    public readonly APP_PERMIT_PROJECT_REPORT       = `APP_PERMIT_PROJECT_REPORT`;
    public readonly APP_PERMIT_PROJECT_DOWNLOAD     = `APP_PERMIT_PROJECT_LIST` // `APP_PERMIT_PROJECT_DOWNLOAD`;

    /**
     * AUDITOR (ANALISTA)
     */
    // ESTADOS [STATE]
    public readonly APP_PERMIT_CONFIG_STATE_LIST         = `APP_PERMIT_CONFIG_STATE_LIST`;
    public readonly APP_PERMIT_CONFIG_STATE_SHOW         = `APP_PERMIT_CONFIG_STATE_SHOW`;
    public readonly APP_PERMIT_CONFIG_STATE_CREATE       = `APP_PERMIT_CONFIG_STATE_CREATE`;
    public readonly APP_PERMIT_CONFIG_STATE_UPDATE       = `APP_PERMIT_CONFIG_STATE_UPDATE`;
    public readonly APP_PERMIT_CONFIG_STATE_DELETE       = `APP_PERMIT_CONFIG_STATE_DELETE`;
    public readonly APP_PERMIT_CONFIG_STATE_RECOVERY     = `APP_PERMIT_CONFIG_STATE_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_STATE_REPORT       = `APP_PERMIT_CONFIG_STATE_REPORT`;
    public readonly APP_PERMIT_CONFIG_STATE_DOWNLOAD     = `APP_PERMIT_CONFIG_STATE_LIST` // `APP_PERMIT_PROJECT_DOWNLOAD`;
    
    // MUNICIPIOS [PROJECT]
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_LIST         = `APP_PERMIT_CONFIG_MUNICIPIO_LIST`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_SHOW         = `APP_PERMIT_CONFIG_MUNICIPIO_SHOW`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_CREATE       = `APP_PERMIT_CONFIG_MUNICIPIO_CREATE`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_UPDATE       = `APP_PERMIT_CONFIG_MUNICIPIO_UPDATE`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_DELETE       = `APP_PERMIT_CONFIG_MUNICIPIO_DELETE`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_RECOVERY     = `APP_PERMIT_CONFIG_MUNICIPIO_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_REPORT       = `APP_PERMIT_CONFIG_MUNICIPIO_REPORT`;
    public readonly APP_PERMIT_CONFIG_MUNICIPIO_DOWNLOAD     = `APP_PERMIT_CONFIG_MUNICIPIO_LIST` // `APP_PERMIT_CONFIG_MUNICIPIO_DOWNLOAD`;

    // PARRAOQUIAS [CONFIG_PARRAOQUIAS]
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_LIST         = `APP_PERMIT_CONFIG_PARRAOQUIAS_LIST`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_SHOW         = `APP_PERMIT_CONFIG_PARRAOQUIAS_SHOW`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_CREATE       = `APP_PERMIT_CONFIG_PARRAOQUIAS_CREATE`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_UPDATE       = `APP_PERMIT_CONFIG_PARRAOQUIAS_UPDATE`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_DELETE       = `APP_PERMIT_CONFIG_PARRAOQUIAS_DELETE`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_RECOVERY     = `APP_PERMIT_CONFIG_PARRAOQUIAS_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_REPORT       = `APP_PERMIT_CONFIG_PARRAOQUIAS_REPORT`;
    public readonly APP_PERMIT_CONFIG_PARRAOQUIAS_DOWNLOAD     = `APP_PERMIT_CONFIG_PARRAOQUIAS_LIST` // `APP_PERMIT_CONFIG_PARRAOQUIAS_DOWNLOAD`;

    // NUCLEOS [CONFIG_NUCLEOS]
    public readonly APP_PERMIT_CONFIG_NUCLEOS_LIST         = `APP_PERMIT_CONFIG_NUCLEOS_LIST`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_SHOW         = `APP_PERMIT_CONFIG_NUCLEOS_SHOW`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_CREATE       = `APP_PERMIT_CONFIG_NUCLEOS_CREATE`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_UPDATE       = `APP_PERMIT_CONFIG_NUCLEOS_UPDATE`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_DELETE       = `APP_PERMIT_CONFIG_NUCLEOS_DELETE`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_RECOVERY     = `APP_PERMIT_CONFIG_NUCLEOS_RECOVERY`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_REPORT       = `APP_PERMIT_CONFIG_NUCLEOS_REPORT`;
    public readonly APP_PERMIT_CONFIG_NUCLEOS_DOWNLOAD     = `APP_PERMIT_CONFIG_NUCLEOS_LIST` // `APP_PERMIT_CONFIG_PARRAOQUIAS_DOWNLOAD`;

    // HISTORIAL [HISTORY]
    public readonly APP_PERMIT_HISTORY_LIST         = `APP_PERMIT_HISTORY_LIST`;
    public readonly APP_PERMIT_HISTORY_SHOW         = `APP_PERMIT_HISTORY_SHOW`;

    /**
     * DASHBOARD
     */

    // PARA LAS CARDS [COUNT]
    public readonly APP_PERMIT_COUNT_USER         = `APP_PERMIT_COUNT_USER`;
    public readonly APP_PERMIT_COUNT_PROJECTS     = `APP_PERMIT_COUNT_PROJECTS`;
    public readonly APP_PERMIT_COUNT_PROGRAM      = `APP_PERMIT_COUNT_PROGRAM`;

    // PARA LOS GRÁFICOS [STATICTIS]
    // GRAFICO PIE USUARIOS
    public readonly APP_PERMIT_STATICTIS_USUARIOS_IN_PERMIT      = `APP_PERMIT_STATICTIS_USUARIOS_IN_PERMIT`;
    // GRAFICO PIE PROYECTOS
    public readonly APP_PERMIT_STATICTIS_PROJECTS_IN_PROGRAM     = `APP_PERMIT_STATICTIS_PROJECTS_IN_PROGRAM`; // programas con más proyectos
    public readonly APP_PERMIT_STATICTIS_PROJECTS_IN_CATEGORY    = `APP_PERMIT_STATICTIS_PROJECTS_IN_CATEGORY`; // categorías con más proyectos
    public readonly APP_PERMIT_STATICTIS_PROJECTS_IN_LINE        = `APP_PERMIT_STATICTIS_PROJECTS_IN_LINE`; // líneas con más proyectos
    public readonly APP_PERMIT_STATICTIS_PROJECTS_IN_HISTORY     = `APP_PERMIT_STATICTIS_PROJECTS_IN_HISTORY`; // top proyectos con más interacciones

    // ANALISTA
    public readonly APP_PERMIT_ANALITIC_SECTION     = `APP_PERMIT_ANALITIC_SECTION`; // programas con más proyectos


    /**
     * PROPIETARIO
     */
    public readonly APP_PERMIT_PROPIETARY_PROJECT           = `APP_PERMIT_PROPIETARY_PROJECT`;
    public readonly APP_PERMIT_PROPIETARY_PROJECT_REPORT    = `APP_PERMIT_PROPIETARY_PROJECT_REPORT`;

    /**
     * ESPECIFICOS
     */
    public readonly APP_PERMIT_SPECIIFIC_PROJECT            = `APP_PERMIT_SPECIIFIC_PROJECT`;
    public readonly APP_PERMIT_SPECIIFIC_PROGRAM            = `APP_PERMIT_SPECIIFIC_PROGRAM`;
    public readonly APP_PERMIT_SPECIIFIC_USER_ADMIN         = `APP_PERMIT_SPECIIFIC_USER_ADMIN`;
    public readonly APP_PERMIT_SPECIIFIC_USER_COORDINADOR   = `APP_PERMIT_SPECIIFIC_USER_COORDINADOR`;
    public readonly APP_PERMIT_SPECIIFIC_USER_ESTUDIANTE    = `APP_PERMIT_SPECIIFIC_USER_ESTUDIANTE`;

    public readonly STATICTICS_CREATE_USER =               `STATICTICS_CREATE_USER`;
    public readonly STATICTICS_CREATE_USER_STUDENT =       `STATICTICS_CREATE_USER_STUDENT`;
    public readonly STATICTICS_CREATE_USER_DOCENTE =       `STATICTICS_CREATE_USER_DOCENTE`;
    public readonly STATICTICS_CREATE_USER_COORDINADOR =   `STATICTICS_CREATE_USER_COORDINADOR`;
    public readonly STATICTICS_CREATE_USER_OBRERO_ADMIN =  `STATICTICS_CREATE_USER_OBRERO_ADMIN`;
    public readonly STATICTICS_CREATE_PROJECT =            `STATICTICS_CREATE_PROJECT`;

    /**
     * REPORTS
     */
    // public readonly APP_PERMIT_REPORT_CATEGORY               = `APP_PERMIT_SPECIIFIC_PROJECT`;
    // public readonly APP_PERMIT_REPORT_PROJECT                = `APP_PERMIT_SPECIIFIC_PROJECT`;


}
