-- CreateTable
CREATE TABLE `staticticsUserForMonth` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `monthName` VARCHAR(191) NOT NULL,
    `monthNumber` INTEGER NOT NULL,
    `totalMonth` INTEGER NOT NULL DEFAULT 0,
    `totalDay1` INTEGER NOT NULL DEFAULT 0,
    `totalDay2` INTEGER NOT NULL DEFAULT 0,
    `totalDay3` INTEGER NOT NULL DEFAULT 0,
    `totalDay4` INTEGER NOT NULL DEFAULT 0,
    `totalDay5` INTEGER NOT NULL DEFAULT 0,
    `totalDay6` INTEGER NOT NULL DEFAULT 0,
    `totalDay7` INTEGER NOT NULL DEFAULT 0,
    `totalDay8` INTEGER NOT NULL DEFAULT 0,
    `totalDay9` INTEGER NOT NULL DEFAULT 0,
    `totalDay10` INTEGER NOT NULL DEFAULT 0,
    `totalDay11` INTEGER NOT NULL DEFAULT 0,
    `totalDay12` INTEGER NOT NULL DEFAULT 0,
    `totalDay13` INTEGER NOT NULL DEFAULT 0,
    `totalDay14` INTEGER NOT NULL DEFAULT 0,
    `totalDay15` INTEGER NOT NULL DEFAULT 0,
    `totalDay16` INTEGER NOT NULL DEFAULT 0,
    `totalDay17` INTEGER NOT NULL DEFAULT 0,
    `totalDay18` INTEGER NOT NULL DEFAULT 0,
    `totalDay19` INTEGER NOT NULL DEFAULT 0,
    `totalDay20` INTEGER NOT NULL DEFAULT 0,
    `totalDay21` INTEGER NOT NULL DEFAULT 0,
    `totalDay22` INTEGER NOT NULL DEFAULT 0,
    `totalDay23` INTEGER NOT NULL DEFAULT 0,
    `totalDay24` INTEGER NOT NULL DEFAULT 0,
    `totalDay25` INTEGER NOT NULL DEFAULT 0,
    `totalDay26` INTEGER NOT NULL DEFAULT 0,
    `totalDay27` INTEGER NOT NULL DEFAULT 0,
    `totalDay28` INTEGER NOT NULL DEFAULT 0,
    `totalDay29` INTEGER NOT NULL DEFAULT 0,
    `totalDay30` INTEGER NOT NULL DEFAULT 0,
    `totalDay31` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staticticsUserForYear` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `totalYear` INTEGER NOT NULL DEFAULT 0,
    `totalMonth1` INTEGER NOT NULL DEFAULT 0,
    `totalMonth2` INTEGER NOT NULL DEFAULT 0,
    `totalMonth3` INTEGER NOT NULL DEFAULT 0,
    `totalMonth4` INTEGER NOT NULL DEFAULT 0,
    `totalMonth5` INTEGER NOT NULL DEFAULT 0,
    `totalMonth6` INTEGER NOT NULL DEFAULT 0,
    `totalMonth7` INTEGER NOT NULL DEFAULT 0,
    `totalMonth8` INTEGER NOT NULL DEFAULT 0,
    `totalMonth9` INTEGER NOT NULL DEFAULT 0,
    `totalMonth10` INTEGER NOT NULL DEFAULT 0,
    `totalMonth11` INTEGER NOT NULL DEFAULT 0,
    `totalMonth12` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staticticsUserForCentury` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `totalYear` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staticticsProjectForMonth` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `monthName` VARCHAR(191) NOT NULL,
    `monthNumber` INTEGER NOT NULL,
    `totalMonth` INTEGER NOT NULL DEFAULT 0,
    `totalDay1` INTEGER NOT NULL DEFAULT 0,
    `totalDay2` INTEGER NOT NULL DEFAULT 0,
    `totalDay3` INTEGER NOT NULL DEFAULT 0,
    `totalDay4` INTEGER NOT NULL DEFAULT 0,
    `totalDay5` INTEGER NOT NULL DEFAULT 0,
    `totalDay6` INTEGER NOT NULL DEFAULT 0,
    `totalDay7` INTEGER NOT NULL DEFAULT 0,
    `totalDay8` INTEGER NOT NULL DEFAULT 0,
    `totalDay9` INTEGER NOT NULL DEFAULT 0,
    `totalDay10` INTEGER NOT NULL DEFAULT 0,
    `totalDay11` INTEGER NOT NULL DEFAULT 0,
    `totalDay12` INTEGER NOT NULL DEFAULT 0,
    `totalDay13` INTEGER NOT NULL DEFAULT 0,
    `totalDay14` INTEGER NOT NULL DEFAULT 0,
    `totalDay15` INTEGER NOT NULL DEFAULT 0,
    `totalDay16` INTEGER NOT NULL DEFAULT 0,
    `totalDay17` INTEGER NOT NULL DEFAULT 0,
    `totalDay18` INTEGER NOT NULL DEFAULT 0,
    `totalDay19` INTEGER NOT NULL DEFAULT 0,
    `totalDay20` INTEGER NOT NULL DEFAULT 0,
    `totalDay21` INTEGER NOT NULL DEFAULT 0,
    `totalDay22` INTEGER NOT NULL DEFAULT 0,
    `totalDay23` INTEGER NOT NULL DEFAULT 0,
    `totalDay24` INTEGER NOT NULL DEFAULT 0,
    `totalDay25` INTEGER NOT NULL DEFAULT 0,
    `totalDay26` INTEGER NOT NULL DEFAULT 0,
    `totalDay27` INTEGER NOT NULL DEFAULT 0,
    `totalDay28` INTEGER NOT NULL DEFAULT 0,
    `totalDay29` INTEGER NOT NULL DEFAULT 0,
    `totalDay30` INTEGER NOT NULL DEFAULT 0,
    `totalDay31` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staticticsProjectForYear` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `totalYear` INTEGER NOT NULL DEFAULT 0,
    `totalMonth1` INTEGER NOT NULL DEFAULT 0,
    `totalMonth2` INTEGER NOT NULL DEFAULT 0,
    `totalMonth3` INTEGER NOT NULL DEFAULT 0,
    `totalMonth4` INTEGER NOT NULL DEFAULT 0,
    `totalMonth5` INTEGER NOT NULL DEFAULT 0,
    `totalMonth6` INTEGER NOT NULL DEFAULT 0,
    `totalMonth7` INTEGER NOT NULL DEFAULT 0,
    `totalMonth8` INTEGER NOT NULL DEFAULT 0,
    `totalMonth9` INTEGER NOT NULL DEFAULT 0,
    `totalMonth10` INTEGER NOT NULL DEFAULT 0,
    `totalMonth11` INTEGER NOT NULL DEFAULT 0,
    `totalMonth12` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `staticticsProjectForCentury` (
    `id` VARCHAR(191) NOT NULL,
    `objectName` VARCHAR(191) NULL,
    `objectReferenceId` VARCHAR(191) NOT NULL DEFAULT 'biblioteca',
    `year` INTEGER NOT NULL,
    `totalYear` INTEGER NOT NULL DEFAULT 0,
    `updateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
